#!/usr/bin/env python3
"""
Convert Hiwonder JSON .rob action group files to binary PROGMEM C arrays.

Usage:
    python3 convert_rob_files.py <input_folder> <output_header>

Example:
    python3 convert_rob_files.py "../../10. Action Group Files" ../action_group_uploader/action_group_data.h

The JSON .rob format (from Hiwonder PC software):
    { "robot": "MiniHexa", "Actions": [ { "Duration": 400, "Servos": [1505, 1228, ...] }, ... ] }

The binary .rob format (expected by ESP32 SPIFFS):
    [1 byte: total_frames]
    [58-byte frames × N]:
        [0] frame_index (1-based)
        [1] control_num (18)
        [2] time_low
        [3] time_high
        [4 + i*3] servo_id (i+1)
        [5 + i*3] duty_low
        [6 + i*3] duty_high
"""

import json
import os
import re
import sys


def json_to_binary(json_path):
    """Convert a JSON .rob file to binary bytes."""
    with open(json_path, 'r') as f:
        data = json.load(f)

    actions = data.get('Actions', [])
    num_frames = len(actions)

    binary = bytearray()
    binary.append(num_frames)  # First byte: total frame count

    for i, action in enumerate(actions):
        frame = bytearray(58)
        frame[0] = i + 1                          # frame_index (1-based)
        frame[1] = 18                              # control_num (always 18 servos)
        duration = action['Duration']
        frame[2] = duration & 0xFF                 # time_low
        frame[3] = (duration >> 8) & 0xFF          # time_high

        servos = action['Servos']
        for j in range(min(18, len(servos))):
            servo_id = j + 1                       # servo IDs are 1-based
            duty = servos[j]
            frame[4 + j * 3] = servo_id
            frame[5 + j * 3] = duty & 0xFF        # duty_low
            frame[6 + j * 3] = (duty >> 8) & 0xFF  # duty_high

        binary.extend(frame)

    return binary, num_frames


def extract_id(filename):
    """Extract the action group number from filename like 'No.14 Wave.rob'."""
    match = re.match(r'No\.(\d+)', filename)
    if match:
        return int(match.group(1))
    return None


def generate_header(input_folder, output_path):
    """Generate a C header file with PROGMEM arrays for all .rob files."""
    rob_files = sorted(
        [f for f in os.listdir(input_folder) if f.endswith('.rob')],
        key=lambda x: extract_id(x) or 0
    )

    if not rob_files:
        print("No .rob files found!")
        return

    lines = []
    lines.append("// Auto-generated action group data — do not edit manually")
    lines.append("// Generated by convert_rob_files.py")
    lines.append(f"// Source: {os.path.basename(input_folder)}/")
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append("")

    ag_info = []  # (id, num_frames, binary_size, name)

    for fname in rob_files:
        ag_id = extract_id(fname)
        if ag_id is None:
            print(f"Skipping {fname} — could not extract ID")
            continue

        json_path = os.path.join(input_folder, fname)
        binary, num_frames = json_to_binary(json_path)
        name = fname.replace('.rob', '').replace(f'No.{ag_id} ', '')
        ag_info.append((ag_id, num_frames, len(binary), name))

        lines.append(f"// Action Group {ag_id}: {name} ({num_frames} frames, {len(binary)} bytes)")
        lines.append(f"const uint8_t PROGMEM ag_{ag_id}_data[] = {{")

        # Format as rows of 20 bytes
        for row_start in range(0, len(binary), 20):
            row = binary[row_start:row_start + 20]
            hex_vals = ", ".join(f"0x{b:02X}" for b in row)
            comma = "," if row_start + 20 < len(binary) else ""
            lines.append(f"    {hex_vals}{comma}")

        lines.append("};")
        lines.append(f"const size_t ag_{ag_id}_size = sizeof(ag_{ag_id}_data);")
        lines.append("")

    # Summary struct and table
    lines.append("// === Action Group Registry ===")
    lines.append("struct ActionGroupInfo {")
    lines.append("    uint8_t id;")
    lines.append("    const uint8_t* data;")
    lines.append("    size_t size;")
    lines.append("    uint8_t num_frames;")
    lines.append("    const char* name;")
    lines.append("};")
    lines.append("")
    lines.append(f"const int NUM_ACTION_GROUPS = {len(ag_info)};")
    lines.append("const ActionGroupInfo action_groups[] = {")
    for ag_id, num_frames, size, name in ag_info:
        lines.append(f'    {{{ag_id}, ag_{ag_id}_data, ag_{ag_id}_size, {num_frames}, "{name}"}},')
    lines.append("};")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated {output_path}")
    print(f"  {len(ag_info)} action groups, {sum(s for _, _, s, _ in ag_info)} bytes total")
    for ag_id, num_frames, size, name in ag_info:
        print(f"  AG{ag_id:2d}: {name} ({num_frames} frames, {size} bytes)")


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input_folder> <output_header>")
        sys.exit(1)

    generate_header(sys.argv[1], sys.argv[2])
